// Mocks generated by Mockito 5.4.5 from annotations
// in pokemon_app_global66/test/features/home/domain/usecases/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemon_app_global66/features/home/domain/entities/ability_detail_entity.dart'
    as _i4;
import 'package:pokemon_app_global66/features/home/domain/entities/pokemon_detail_entity.dart'
    as _i2;
import 'package:pokemon_app_global66/features/home/domain/entities/pokemon_entity.dart'
    as _i7;
import 'package:pokemon_app_global66/features/home/domain/entities/pokemon_species_entity.dart'
    as _i3;
import 'package:pokemon_app_global66/features/home/domain/repositories/favorite_repository.dart'
    as _i8;
import 'package:pokemon_app_global66/features/home/domain/repositories/pokemon_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonDetailEntity_0 extends _i1.SmartFake
    implements _i2.PokemonDetailEntity {
  _FakePokemonDetailEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonSpeciesEntity_1 extends _i1.SmartFake
    implements _i3.PokemonSpeciesEntity {
  _FakePokemonSpeciesEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAbilityDetailEntity_2 extends _i1.SmartFake
    implements _i4.AbilityDetailEntity {
  _FakeAbilityDetailEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i5.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.PokemonEntity>> getPokemons({
    int? offset = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [],
          {
            #offset: offset,
            #limit: limit,
          },
        ),
        returnValue:
            _i6.Future<List<_i7.PokemonEntity>>.value(<_i7.PokemonEntity>[]),
      ) as _i6.Future<List<_i7.PokemonEntity>>);

  @override
  _i6.Future<_i2.PokemonDetailEntity> getPokemonDetail(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonDetail,
          [name],
        ),
        returnValue: _i6.Future<_i2.PokemonDetailEntity>.value(
            _FakePokemonDetailEntity_0(
          this,
          Invocation.method(
            #getPokemonDetail,
            [name],
          ),
        )),
      ) as _i6.Future<_i2.PokemonDetailEntity>);

  @override
  _i6.Future<_i3.PokemonSpeciesEntity> getPokemonSpecies(
    int? id,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonSpecies,
          [
            id,
            languageCode,
          ],
        ),
        returnValue: _i6.Future<_i3.PokemonSpeciesEntity>.value(
            _FakePokemonSpeciesEntity_1(
          this,
          Invocation.method(
            #getPokemonSpecies,
            [
              id,
              languageCode,
            ],
          ),
        )),
      ) as _i6.Future<_i3.PokemonSpeciesEntity>);

  @override
  _i6.Future<_i4.AbilityDetailEntity> getAbilityDetail(
    String? abilityName,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAbilityDetail,
          [
            abilityName,
            languageCode,
          ],
        ),
        returnValue: _i6.Future<_i4.AbilityDetailEntity>.value(
            _FakeAbilityDetailEntity_2(
          this,
          Invocation.method(
            #getAbilityDetail,
            [
              abilityName,
              languageCode,
            ],
          ),
        )),
      ) as _i6.Future<_i4.AbilityDetailEntity>);
}

/// A class which mocks [FavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRepository extends _i1.Mock
    implements _i8.FavoriteRepository {
  MockFavoriteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.PokemonDetailEntity>> getFavorites() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i6.Future<List<_i2.PokemonDetailEntity>>.value(
            <_i2.PokemonDetailEntity>[]),
      ) as _i6.Future<List<_i2.PokemonDetailEntity>>);

  @override
  _i6.Future<void> addFavorite(_i2.PokemonDetailEntity? pokemon) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [pokemon],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFavorite(int? pokemonId) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [pokemonId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isFavorite(int? pokemonId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [pokemonId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Stream<List<_i2.PokemonDetailEntity>> watchFavorites() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchFavorites,
          [],
        ),
        returnValue: _i6.Stream<List<_i2.PokemonDetailEntity>>.empty(),
      ) as _i6.Stream<List<_i2.PokemonDetailEntity>>);
}
